name: ubuild
description: Radxa U-Boot Build Tool
inputs:
  board:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: radxa-repo/ubuild
    - name: Install dependency
      shell: bash
      run: |
        sudo apt install gcc-aarch64-linux-gnu gcc-arm-none-eabi device-tree-compiler
        sudo gem i fpm -f
    - name: Build
      shell: bash
      run: |
        mkdir .output
        pushd .output
        ../ubuild ${{ inputs.board }}
        popd
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: .output/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}