name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.query.outputs.boards }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Query available board configs
        id: query
        run: |
          echo "::set-output name=boards::$(./ubuild --json boards)"
  build:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: ${{fromJSON(needs.query.outputs.boards)}}
    steps:
      - name: Build
        uses: radxa-repo/ubuild@main
        with:
          board: ${{ matrix.boards }}